export const NAMES_GET_ALL = "NAMES_GET_ALL";
export const NAMES_EDIT = "NAMES_EDIT";
export const NAMES_ADD = "NAMES_ADD";
export const NAMES_DELETE = "NAMES_DELETE";
export const GET_PAGINATION_DETAILS = "GET_PAGINATION_DETAILS";
